I have this ansible code that tries to log in a user.  I was told to get rid of the ignore_errors: true and instead use change_when or failed_when with a result code.
This task is successful when the user fails to log in.  The expected output is that they can't log in, there should be an error code and it should move onto the next task.  


    - name: Log in fail attempt for {{ test_username }}
      ansible.windows.win_shell: |
        Write-Output "This should not run."
      vars:
        ansible_become: true
        ansible_become_method: runas
        ansible_become_user: '.\\{{ test_username }}'
        ansible_become_password: "{{ test_password }}"
        ansible_become_flags: "logon_type=interactive"
      register: identity
      # ignore_errors: true
      no_log: true
